### PR TITLE
0.0.8 - Remembering past conversions via cache map JSON; dry runs; update documentation

### PR DESCRIPTION
**Pull request by baublet**
Solves #10 and #17 by adding:

- a `dry-run` flag
- the default ability to remember the files already compressed so we don't hammer the TinyPNG API
- the ability to change the above and commit to VC via the `-c, --cache` flag
- updated documentation to reflect the above

Also added:
- format some of the code previously not formatted using prettier.js
- Support for a maximum runs per command flag and documented its use (`-m, --max`)

### CODE REVIEW

**Comment by romanlex** [comment]
@rasshofer merge it please)

**Comment by eddiewp** [comment]
merge it

please

**Comment by MikeSpitz** [comment]
@rasshofer 
@maxkueng
@tholu
@mvenghaus
@jblok
@tomatolicious
@kolya182

Is this module still being maintained? There are some good fixes in here.

**Comment by tomatolicious** [comment]
> @rasshofer
> @maxkueng
> @tholu
> @mvenghaus
> @jblok
> @tomatolicious
> @kolya182
> 
> Is this module still being maintained? There are some good fixes in here.

I wish it was - but it seems abandoned as of now. I had already contacted the original maintainer  by email some years back but have received no response.

**Comment by tholu** [comment]
Would be great to have this merged, @rasshofer what do you think? Otherwise, forking is always an option.

**Comment by rasshofer** [comment]
I’ll try to have a look at it within the next days, sorry for the delay.

**Comment by rasshofer** [comment]
I’ll add some additional stuff like a dedicated Prettier config and better linting/testing/tooling and release this one afterwards. Thank you @baublet for the new features and sorry once again for the delay.

**Comment by baublet** [comment]
Hah! I've got a new job since I made this PR, but I'm glad this was helpful to you! Apologies for not following up myself. My GH notifications are nightmare 😬

**Pull request merged**
